[package]
authors.workspace = true
categories.workspace = true
description = "The convenience of SQLite – but with PostgreSQL (Testing package)"
edition.workspace = true
keywords.workspace = true
license.workspace = true
name = "pgdo-test"
readme = "README.md"
repository.workspace = true
version.workspace = true

# Don't accidentally publish this crate.
publish = false

[lib]
proc-macro = true
name = "pgdo_test"
path = "src/lib.rs"

[dependencies]
quote = "^1.0.33"
syn = "^2.0.38"
pgdo-lib = { version = "0.3.1", path = "../pgdo-lib" }

[dev-dependencies]

[build-dependencies]
pgdo-lib = { version = "0.3.1", path = "../pgdo-lib" }
prettyplease = "^0.2.15"
quote = "^1.0.33"
syn = "^2.0.38"
wax = "^0.6.0"
