name: pgdo CI

on:
  push:
  schedule:
    - cron: "0 0 * * 0" # weekly

jobs:
  test:
    name: Test
    runs-on: ubicloud-standard-8
    steps:
      - uses: actions/checkout@v6
      # Install Rust.
      - uses: dtolnay/rust-toolchain@stable
      # Install PostgreSQL runtimes.
      - name: Set up PostgreSQL APT repository
        run: |
          # From https://wiki.postgresql.org/wiki/Apt
          sudo apt-get install -y postgresql-common
          sudo sh /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh -y
      - name: Install various PostgreSQL versions
        run: |
          # Install every version that pgdo supports, i.e. from
          # `pgdo::runtime::MINIMUM_VERSION` onwards. See
          # https://www.postgresql.org/support/versioning/ for official support
          # information, and https://apt.postgresql.org/pub/repos/apt/ for all
          # available versions.
          sudo apt-get install -y postgresql-{15,16,17,18}
      - name: Set PATH for all PostgreSQL runtimes
        run: |
          printf '%s\n' /usr/lib/postgresql/*/bin | sort -Vr | tee -a "$GITHUB_PATH"
      # Smoke-test the command-line tool.
      - name: Run a command in a cluster with pgdo
        run: cargo run --package pgdo-cli -- exec --destroy -- psql --no-psqlrc --command 'SELECT version()'
      # Finally, run tests.
      - run: cargo test

  fmt:
    name: Rustfmt
    runs-on: ubicloud-standard-2
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - run: cargo fmt --all -- --check

  clippy:
    name: Clippy # i.e. `cargo check` plus extra linting.
    runs-on: ubicloud-standard-2
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - run: cargo clippy --all-targets -- -D warnings
